# Generated by Django 4.0.6 on 2022-09-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0005_escuela_reserva_torneo_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=38)),
                ('horario', models.CharField(max_length=38)),
                ('sedes', models.CharField(max_length=38)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deporte', models.CharField(max_length=38)),
                ('horario', models.CharField(max_length=38)),
                ('sedes', models.CharField(max_length=38)),
                ('categoría', models.CharField(max_length=38)),
            ],
        ),
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Reservas',
        ),
        migrations.DeleteModel(
            name='Escuela',
        ),
        migrations.DeleteModel(
            name='Torneo',
        ),
    ]
